@pending.throw.sets_current_exception() {
  :
}

@pending.throw.Exception_is_caught_by_most_recently_defined_catch_function() {
  :
}

@pending.throw.stops_program_execution_if_not_caught_by_any_handlers() {
  # T_STOPPED
  :
}

@pending.throw.can_throw_an_existing_exception_instance() {
  :
}

@pending.throw.creates_a_new_exception_instance_with_provided_message() {
  :
}

@pending.throw.includes_the_line_of_code_from_shell_source_file_which_called_throw() {
  :
}

@pending.throw.include_a_copy_of_the_backtrace_from_the_time_throw_was_called() {
  :
}